# Generated by Django 3.0 on 2019-12-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knots', '0002_auto_20191203_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('knot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knots.Knot')),
            ],
        ),
    ]
